version: '3.4'

services:
  pythondevelopment:
    image: pythondevelopment
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 test_problem.py runserver 0.0.0.0:undefined --nothreading --noreload"]
    ports:
      - 5678:5678
